### ISSUE TITLE
Not working when running via -c parameter

### ISSUE THREAD

**Issue by RootLUG** [Qix-/better-exceptions#17]
It doesn't work if you run commands by directly passing it to python interpreter via -c cli flag.

Can be reproduced using:
`python -c "import better_exceptions; val=3; assert val > 10"`

**Comment by Qix-** [comment]
What does it do instead?

**Comment by Qix-** [comment]
For future reference - simple method hooking:

```python
import functools

def wrap_function(oldfunction, newfunction):
    @functools.wraps(oldfunction)
    def run(*args, **kwargs):
        return newfunction(oldfunction, *args, **kwargs)
    return run


class Foo(object):
    def __init__(self, v):
        self.val = v

    def bar(self):
        print 'value: {}'.format(self.val)


def override_bar(old_fn, *args):
    print 'OVERRIDE'
    return old_fn(*args);


f1 = Foo(10)

f1.bar()

setattr(Foo, 'bar', wrap_function(getattr(Foo, 'bar'), override_bar))

f2 = Foo(20)
f1.bar()
f2.bar()
```

**Comment by Qix-** [comment]
Alright, so this isn't possible without some _extreme_ hacks - hacks that I don't think should be supported since they would rely _solely_ on cpython's implementation internals.

I dove in _deep_ into the CPython source code, and the default interactive shell never drops into the Python context (i.e. everything happens in the C world). This means there is nothing I can hook into to really help us out here.

However, there _is_ one way, though I'm not sure if it would be useful at all, and that is to extend `code.InteractiveConsole` to include the information about the last run command. However, that means you would have to run `python -m better_exceptions` to drop into a fake interactive session.

If that's okay with the community, then I will re-open and implement this.

**Comment by Qix-** [comment]
Also, there is this problem:

```
>>> assert 5 > 10
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AssertionError
>>> def foo(a):
...     assert a > 10
...
>>> foo(10)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<console>", line 2, in foo
AssertionError
>>>
```

Python just doesn't store enough information for me to really do much of anything here.

This module _does_ work, but only when the frames are for code loaded in via a file.

**Comment by Qix-** [comment]
I lied. I'm going to implement this.

I haven't released it yet, but you can do `python -m better_exceptions` to drop into a REPL that properly supports code entered via the command line.

Further, I'm writing a way to get the code from the `-c` flag. It's not easy since Python isn't really helping us out here.

**Comment by Qix-** [comment]
Apologies for the comment spam; this is actually a _really hard_ feature, but there's headway!

Here's what the output looks like now:

<img width="580" alt="screen shot 2017-03-24 at 12 37 19 am" src="https://cloud.githubusercontent.com/assets/885648/24284789/49bc4ee2-102a-11e7-92f4-438fe51a1484.png">

Implementing this feature turned up a few bugs that have since been fixed and presented a really, really fun engineering problem.

This only works on posix platforms for now. I intend to add Windows support soon, along with improved support on Linux. Will release when I do so.

Thanks for the challenge! The latest code is on master; give it a shot.

**Comment by RootLUG** [comment]
Wow that was fast. Better Exceptions now rocks even more! Really good job

**Comment by Qix-** [comment]
Closing; for windows support, please see #27.
