### ISSUE TITLE
Support logging

### ISSUE THREAD

**Issue by ulope** [Qix-/better-exceptions#21]
Python's logging module has the ability to output tracebacks alongside log messages if inside an exception context ([`Logger.<level_method>(..., exc_info=True)`](https://docs.python.org/3.6/library/logging.html#logging.Logger.debug) and [`Logger.exception(...)`](https://docs.python.org/3.6/library/logging.html#logging.Logger.exception)).

It would be great if better exceptions could also inject it's enhanced traceback rendering there.

**Comment by Qix-** [comment]
Sure! I'll take a look later today.

**Comment by Qix-** [comment]
Can you test the latest master? :)

**Comment by nilleb** [comment]
Doesn't work for me.
1. isatty (in colors.py) can throw OSError (on some exotic environments like GAE)
2. more to come (the format_exception is not being called, I still don't know why. I am using a custom logging.Formatter, this is possibly the reason for which it doesn't work)

**Comment by Qix-** [comment]
1. Good to know, I didn't realize it would throw on certain platforms. I'll fix that.
2. Right, custom formatters will need to handle it and call `format_exception` themselves. The only logger formatter that I override is the _default_ `StreamHandler`'s formatter on Python 2.7 and `_StderrHandler` on Python 3.x. I didn't want to be too intrusive seeing as how I didn't want to change how existing programs worked if they had very specific requirements from their logging formatters.

However, if you add `format_exception` to your custom formatter, you'll need a lambda:

```python
from better_exceptions import format_exception
formatException = lambda exc_info: format_exception(*exc_info)
```

I haven't decided on the API yet since it appears the formatter function for exceptions is one of the few places in the standard Python API that accepts the typical triple of `exc_info` values as a triple instead of three unpacked arguments.

So either I break the API convention in `better_exceptions` and have `format_exception` accept a triple, or I require that you use a lambda to expand the arguments and keep `format_exception` as the three-argument version.
