### ISSUE TITLE
navigating keys are shown as control characters when in better-exceptions python3 REPL on ubuntu

### ISSUE THREAD

**Issue by sonack** [Qix-/better-exceptions#54]
OS: ubuntu 16.04 LTS
Interpreter: Python 3.6.2 :: Anaconda, Inc.
terminal: gnome 3.18.3 (I think it will helps)
Symptom:  Just like the vim-minimal when I just installed my os, the up, down , left and right arrow navigating keys are not work as I expected, they will only print  `^[[A`  .... `^[[D` on the REPL.

**Comment by Qix-** [comment]
Does the same happen with the regular REPL?

Further, do you have a [`.pythonrc`](https://stackoverflow.com/a/246779) script set up?

**Comment by sonack** [comment]
@Qix-   This doesn't happened to the regular REPL, I don't find anything like a `.pythonrc` script.

**Comment by Qix-** [comment]
Sorry for the delay in response. I don't assume you're still playing around with this almost a year later, but the problem here is that `readline` isn't being intialized in your REPL. Setting up a proper [`.pythonrc`](https://github.com/whiteinge/dotfiles/blob/master/.pythonrc.py) is important for this (search in-page for `readline` and copy all relevant parts).

I'm not sure how much we can do to support out of the box. Let me know if that doesn't solve the problem and I can investigate further.
