### ISSUE TITLE
PTH files may be deprecated

### ISSUE THREAD

**Issue by stuaxo** [Qix-/better-exceptions#95]
I don't know if you have seen this python issue to deprecate PTH files.

https://bugs.python.org/issue33944

One of my projects, [vext](http://github.com/stuaxo/vext/) also uses PTH files, but I haven't had time to weigh in on the issue above.

I feel, like we both our libraries have a legitimate use-case, so hope this doesn't disappear without some replacement for running code at startup.

**Comment by Qix-** [comment]
Thank you for bringing this to my attention, I've responded to the issue.

It really sounds like someone had a bad time with some .PTH related code and wanted to kill the whole thing off without really thinking much about it.

There's a shockingly low amount of "let's fix it instead of kill it", which I don't like to see coming from _any_ development community - let alone Python's.

**Comment by Qix-** [comment]
Closing for now as there's nothing much I can do beyond this point. Thank you again for letting me know!

**Comment by stuaxo** [comment]
Yeah, just a heads up really.

Similarly, there seems to be a the same mentality with `pip` ... I understand they want to make everything more simple (separate installation from configuration apparently), but I find it convenient being able to install + configure from one place.

/rant over.

**Comment by stuaxo** [comment]
Maybe in the longer term having a pep for import hooks seperate from pth files would be an idea, along much like better_exceptions these could be gated behind environment variables or some sort of config in the virtualenv itself.
